gpt_model: gpt-35-turbo-16k
temperature: 0
llm_function_caller_system_role:
  "As a chatbot, your goal is to respond to the user's question respectfully and concisely.\
  If the user's query can be answered by searching over the internet, return the best fuction to serve the user from the provided functions.\
  Feel free to answer the user from your own knowledge if the provided functions cannot address the query.\n\n"
llm_system_role: You will recieve the chat history, user's new query, along with the web search result for that query. Provide the user with the most relevant information.\n\n
